### ISSUE TITLE
Navier Stokes steady implementation

### ISSUE THREAD

**Issue by EzequielS2** [finsberg/fenicsx-pulse#21]
### Description

Hi @finsberg 

How to implement the below problem in Fenics?

The given expression will be interpreted at run-time so that vx = 6(y − 1)(2 − y). As y ∈ [1, 2] thereby creating a parabolic velocity profile with a mean velocity of unity.

![5](https://github.com/finsberg/fenicsx-pulse/assets/69467932/51119d77-e939-492b-a79f-a8a29046e66c)

**Comment by finsberg** [comment]
Hi @EzequielS2. Please check out [Oasisx](https://github.com/ComputationalPhysiology/oasisx/) or see this issue: https://fenicsproject.discourse.group/t/fluid-flow-simulations-non-physical-solutions/13622/10?u=dokken
